# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1484, 1726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(600, 16777215))
        self.label.setStyleSheet("\n"
"background-image: url(:/newPrefix/leaf.png);\n"
"border-radius:5px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/leaf.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(650, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(900, 16777215))
        self.frame_3.setStyleSheet("margin-left:100px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_page = QtWidgets.QPushButton(self.frame_3)
        self.login_page.setStyleSheet(" font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 34px;\n"
"            line-height: 38px;\n"
"            color: #5F7C8D;\n"
"background-color: transparent;")
        self.login_page.setObjectName("login_page")
        self.verticalLayout.addWidget(self.login_page)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setStyleSheet("position: absolute;\n"
"            width: 90px;\n"
"            height: 0px;\n"
"            left: -23px;\n"
"            top: 52px;\n"
"            border: 3px solid #5F7C8D;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.signup = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Istok Web")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.signup.setFont(font)
        self.signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup.setStyleSheet(" font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 34px;\n"
"            line-height: 38px;\n"
"            color: #5F7C8D;\n"
"background-color: transparent;")
        self.signup.setObjectName("signup")
        self.gridLayout_2.addWidget(self.signup, 1, 1, 1, 1)
        self.password = QtWidgets.QLineEdit(self.frame_3)
        self.password.setStyleSheet("background: transparent;\n"
"            font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-size: 28px;\n"
"            color: rgba(95, 124, 141, 0.55);\n"
" letter-spacing: 0.75px;\n"
" border: none;\n"
"border-bottom:2.5px solid #5F7C8D;")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout_2.addWidget(self.password, 3, 0, 1, 2)
        self.Login_button = QtWidgets.QPushButton(self.frame_3)
        self.Login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login_button.setStyleSheet(" position: absolute;\n"
"            width: 432px;\n"
"            height: 73px;\n"
"            left: 691px;\n"
"            top: 581px;\n"
"            background: #4B687A;\n"
" font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 28px;\n"
"color : white")
        self.Login_button.setObjectName("Login_button")
        self.gridLayout_2.addWidget(self.Login_button, 4, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 90))
        self.label_2.setStyleSheet("\n"
"\n"
"font-family: \'Istok Web\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 54px;\n"
"line-height: 92px;\n"
"\n"
"color: #7A999C;\n"
"background : transparent;\n"
"margin-bottom:40px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 2)
        self.username = QtWidgets.QLineEdit(self.frame_3)
        self.username.setStyleSheet("background: transparent;\n"
"            font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-size: 28px;\n"
"            color: rgba(95, 124, 141, 0.55);\n"
" letter-spacing: 0.75px;\n"
"border: none;\n"
"border-bottom:2.5px solid #5F7C8D;")
        self.username.setObjectName("username")
        self.gridLayout_2.addWidget(self.username, 2, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1484, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_page.setText(_translate("MainWindow", "Login"))
        self.signup.setText(_translate("MainWindow", "SignUp"))
        self.password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Login_button.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "Welcome"))
        self.username.setPlaceholderText(_translate("MainWindow", "Username"))
import stripes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
