# -*- coding: utf-8 -*-

<<<<<<< HEAD

=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
# Form implementation generated from reading ui file '.\calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


<<<<<<< HEAD


=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
<<<<<<< HEAD
from PyQt5.QtWidgets import QListWidgetItem, QMainWindow
=======
from PyQt5.QtWidgets import QListWidgetItem
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
from PyQt5.QtCore import Qt
from PyQt5.QtCore import Qt, QDate,QTimer
from PyQt5.QtWidgets import QMessageBox
from plyer import notification

<<<<<<< HEAD

import time


class Reminder(QMainWindow):
    def __init__(self):
        super(Reminder, self).__init__()
        self.setupUi(self)
        
=======
import time

class Reminder(object):
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 538)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
"  border: none;\n"
"  background-color: transparent;\n"
"  color: #FFF; /* Specify a default color */\n"
"}\n"
"\n"
"#centralwidget {\n"
"  background-color: white\n"
";\n"
"}\n"
"\n"
"#side_menu {\n"
"  background-color: #071e26;\n"
"  border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  padding: 10px;\n"
"  background-color: #071e26;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"#main_body {\n"
"  background-color: #071e26;\n"
"  border-radius: 10px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 70))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("\n"
"                font-family: \'Istok Web\';\n"
"                font-weight: 700;\n"
"                font-size: 20px;\n"
"         \n"
"\n"
"            ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons_folder/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QWidget(self.frame_2)
        self.side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.side_menu)
        self.frame_4.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Home_button = QtWidgets.QPushButton(self.frame_4)
        self.Home_button.setMinimumSize(QtCore.QSize(0, 80))
        self.Home_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Home_button.setStyleSheet("QPushButton {\n"
"                font-family: \'Istok Web\';\n"
"                font-weight: 700;\n"
"                font-size: 20px;\n"
"         \n"
"\n"
"            }\n"
"            QPushButton:hover {\n"
"background-color:rgb(5, 171, 232    );    \n"
"            }\n"
"        \"\"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons_folder/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home_button.setIcon(icon1)
        self.Home_button.setIconSize(QtCore.QSize(20, 20))
        self.Home_button.setObjectName("Home_button")
        self.verticalLayout_3.addWidget(self.Home_button)
        self.Daily_button = QtWidgets.QPushButton(self.frame_4)
        self.Daily_button.setMinimumSize(QtCore.QSize(0, 80))
        self.Daily_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Daily_button.setStyleSheet("QPushButton {\n"
"                font-family: \'Istok Web\';\n"
"                font-weight: 700;\n"
"                font-size: 20px;\n"
"\n"
"\n"
"            }\n"
"            QPushButton:hover {\n"
"background-color:rgb(5, 171, 232    );    \n"
"            }\n"
"        \"\"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons_folder/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Daily_button.setIcon(icon2)
        self.Daily_button.setIconSize(QtCore.QSize(20, 20))
        self.Daily_button.setObjectName("Daily_button")
        self.verticalLayout_3.addWidget(self.Daily_button)
        self.Weekly_button = QtWidgets.QPushButton(self.frame_4)
        self.Weekly_button.setMinimumSize(QtCore.QSize(0, 80))
        self.Weekly_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Weekly_button.setStyleSheet("QPushButton {\n"
"                font-family: \'Istok Web\';\n"
"                font-weight: 700;\n"
"                font-size: 20px;\n"
"\n"
"\n"
"            }\n"
"            QPushButton:hover {\n"
"background-color:rgb(5, 171, 232    );    \n"
"            }\n"
"        \"\"")
        self.Weekly_button.setIcon(icon2)
        self.Weekly_button.setIconSize(QtCore.QSize(20, 20))
        self.Weekly_button.setObjectName("Weekly_button")
        self.verticalLayout_3.addWidget(self.Weekly_button)
        self.Reminder_button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reminder_button.sizePolicy().hasHeightForWidth())
        self.Reminder_button.setSizePolicy(sizePolicy)
        self.Reminder_button.setMinimumSize(QtCore.QSize(20, 80))
        self.Reminder_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Reminder_button.setStyleSheet("QPushButton {\n"
"                font-family: \'Istok Web\';\n"
"                font-weight: 700;\n"
"                font-size: 20px;\n"
"         \n"
"\n"
"            }\n"
"            QPushButton:hover {\n"
"background-color:rgb(5, 171, 232    );    \n"
"            }\n"
"        \"\"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons_folder/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Reminder_button.setIcon(icon3)
        self.Reminder_button.setIconSize(QtCore.QSize(20, 20))
        self.Reminder_button.setObjectName("Reminder_button")
        self.verticalLayout_3.addWidget(self.Reminder_button)
        self.return_button = QtWidgets.QPushButton(self.frame_4)
        self.return_button.setMinimumSize(QtCore.QSize(0, 80))
        self.return_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.return_button.setStyleSheet("QPushButton {\n"
"                font-family: \'Istok Web\';\n"
"                font-weight: 700;\n"
"                font-size: 20px;\n"
"         \n"
"\n"
"            }\n"
"            QPushButton:hover {\n"
"background-color:rgb(5, 171, 232    );    \n"
"            }\n"
"        \"\"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons_folder/arrow-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.return_button.setIcon(icon4)
        self.return_button.setIconSize(QtCore.QSize(20, 20))
        self.return_button.setObjectName("return_button")
        self.verticalLayout_3.addWidget(self.return_button)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.side_menu)
        self.main_body = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.gridLayout = QtWidgets.QGridLayout(self.main_body)
        self.gridLayout.setObjectName("gridLayout")
        self.calendar_frame = QtWidgets.QFrame(self.main_body)
        self.calendar_frame.setStyleSheet("background-color: transparent;\n"
"border-radius:7px;")
        self.calendar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendar_frame.setObjectName("calendar_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.calendar_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.calendar_frame)
        self.calendarWidget.setStyleSheet("color: rgb(85, 255, 255);\n"
"font-size:28px;\n"
"font-weight:700;\n"
"font-family: \'Istok Web\';\n"
"alternate-background-color: rgb(0, 0, 0);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_3.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.calendar_frame, 0, 0, 1, 1)
        self.task_frame = QtWidgets.QFrame(self.main_body)
        self.task_frame.setMaximumSize(QtCore.QSize(550, 16777215))
        self.task_frame.setStyleSheet("background-color: transparent;\n"
"border-radius:7px;")
        self.task_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.task_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.task_frame.setObjectName("task_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.task_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addButton = QtWidgets.QPushButton(self.task_frame)
        self.addButton.setMinimumSize(QtCore.QSize(10, 0))
        self.addButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.addButton.setBaseSize(QtCore.QSize(0, 0))
        self.addButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"font-family: \'Istok Web\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size:12 px;\n"
"color:#071e26;\n"
"border-radius:5px\n"
"\n"
"\n"
"")
        self.addButton.setAutoDefault(False)
        self.addButton.setObjectName("addButton")
        self.gridLayout_2.addWidget(self.addButton, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.task_frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Istok Web")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;\n"
"font-family: \'Istok Web\';\n"
"border-radius:5px;\n"
"letter-spacing:1px;\n"
"font-size:18px;\n"
"padding-left:4px;\n"
"font-weight:400;")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.tasksListWidget = QtWidgets.QListWidget(self.task_frame)
        self.tasksListWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: black;\n"
"font-family: \'Istok Web\';\n"
"font-size:24px;\n"
"font-weight:500;")
        self.tasksListWidget.setObjectName("tasksListWidget")
        item = QtWidgets.QListWidgetItem()
        self.tasksListWidget.addItem(item)
        self.gridLayout_2.addWidget(self.tasksListWidget, 2, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.task_frame)
        self.saveButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"font-family: \'Istok Web\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size:12 px;\n"
"color:#071e26;\n"
"\n"
"\n"
"\n"
"")
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.saveButton, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.task_frame, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.main_body)
        self.main_body.raise_()
        self.side_menu.raise_()
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

<<<<<<< HEAD

=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.menu_expanded = False

<<<<<<< HEAD

        # Connect the button click event to the toggle_menu function
        self.pushButton.clicked.connect(self.toggle_menu)


=======
        # Connect the button click event to the toggle_menu function
        self.pushButton.clicked.connect(self.toggle_menu)

>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        # Set up the animation for the side menu
        self.side_menu_animation = QtCore.QPropertyAnimation(self.side_menu, b"maximumWidth")
        self.side_menu_animation.setDuration(300)

<<<<<<< HEAD

=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        # Set up the central widget animation for overlay effect
        self.central_widget_animation = QtCore.QPropertyAnimation(self.centralwidget, b"geometry")
        self.central_widget_animation.setDuration(300)

<<<<<<< HEAD

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.conn = sqlite3.connect('app_screen_time.db')
=======
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.conn = sqlite3.connect('data.db')
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        self.cursor = self.conn.cursor()
        self.calendarWidget.selectionChanged.connect(self.calendarDateChanged)
        self.calendarDateChanged()
        self.saveButton.clicked.connect(self.saveChanges)
        self.addButton.clicked.connect(self.addNewTask)
<<<<<<< HEAD
        
        
=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
    def calendarDateChanged(self):
            dateSelected = self.calendarWidget.selectedDate().toPyDate()
            # print("Date selected:", dateSelected)
            self.updateTaskList(dateSelected)
<<<<<<< HEAD
           

=======
            
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93

    def updateTaskList(self, date):
        self.tasksListWidget.clear()

<<<<<<< HEAD

        query = "SELECT task, completed FROM tasks WHERE date = ?"
        row = (date,)
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS tasks (
                            task TEXT,
                            completed TEXT,
                            date TEXT
                        )''')
=======
        query = "SELECT task, completed FROM tasks WHERE date = ?"
        row = (date,)
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        results = self.cursor.execute(query, row).fetchall()
        for result in results:
            item = QListWidgetItem(str(result[0]))
            item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
            if result[1] == "YES":
                item.setCheckState(Qt.Checked)
            elif result[1] == "NO":
                item.setCheckState(Qt.Unchecked)
            self.tasksListWidget.addItem(item)

<<<<<<< HEAD

    def saveChanges(self):
        date = self.calendarWidget.selectedDate().toPyDate()


=======
    def saveChanges(self):
        date = self.calendarWidget.selectedDate().toPyDate()

>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        for i in range(self.tasksListWidget.count()):
            item = self.tasksListWidget.item(i)
            task = item.text()
            if item.checkState() == Qt.Checked:
                query = "UPDATE tasks SET completed = 'YES' WHERE task = ? AND date = ?"
            else:
                query = "UPDATE tasks SET completed = 'NO' WHERE task = ? AND date = ?"
            row = (task, date,)
            self.cursor.execute(query, row)
        self.conn.commit()

<<<<<<< HEAD

=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        messageBox = QMessageBox()
        messageBox.setText("Changes saved.")
        messageBox.setStandardButtons(QMessageBox.Ok)
        messageBox.exec()

<<<<<<< HEAD

=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
    def addNewTask(self):
        newTask = str(self.lineEdit.text())  # Use self.lineEdit.text() instead of self.taskLineEdit.text()
        date = self.calendarWidget.selectedDate().toPyDate()

<<<<<<< HEAD

        query = "INSERT INTO tasks(task, completed, date) VALUES (?,?,?)"
        row = (newTask, "NO", date,)


=======
        query = "INSERT INTO tasks(task, completed, date) VALUES (?,?,?)"
        row = (newTask, "NO", date,)

>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        try:
            self.cursor.execute(query, row)
            self.conn.commit()
            self.updateTaskList(date)
            self.lineEdit.clear()  # Clear the lineEdit widget
        except Exception as e:
            print(f"An error occurred: {e}")


<<<<<<< HEAD


=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
    def closeEvent(self, event):
        self.conn.close()
        event.accept()
    def toggle_menu(self):
        # Toggle the menu state
        self.menu_expanded = not self.menu_expanded

<<<<<<< HEAD

        # Define the target width for the side menu
        target_width = 200 if self.menu_expanded else 0


=======
        # Define the target width for the side menu
        target_width = 200 if self.menu_expanded else 0

>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        # Update the side menu animation
        self.side_menu_animation.setEndValue(target_width)
        self.side_menu_animation.start()

<<<<<<< HEAD

=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
        # Update the central widget animation for overlay effect
        if self.menu_expanded:
            self.central_widget_animation.setEndValue(QtCore.QRect(200, 0, 586, 370))
        else:
            self.central_widget_animation.setEndValue(QtCore.QRect(0, 0, 586, 370))
        self.central_widget_animation.start()

<<<<<<< HEAD

=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
    def sendNotification(self, title, message):
        notification.notify(
            title=title,
            message=message,
            timeout=1
        )


<<<<<<< HEAD


=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
    def checkTasksAndSendNotification(self):
        today_date = QDate.currentDate().toString("yyyy-MM-dd")
        query = "SELECT task FROM tasks WHERE date = ? AND completed = 'NO'"
        row = (today_date,)
        tasks = self.cursor.execute(query, row).fetchall()

<<<<<<< HEAD

        if tasks:
            for task in tasks:
                self.sendNotification("Task Notification", task[0])
                time.sleep(3)
    def sendInitialNotifications(self):
       
        QTimer.singleShot(10000, self.checkTasksAndSendNotification)
=======
        if tasks:
            for task in tasks:
                self.sendNotification("Task Notification", task[0])
                time.sleep(3) 
    def sendInitialNotifications(self):
       
        QTimer.singleShot(10000, self.checkTasksAndSendNotification) 
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
                   
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Menu"))
        self.label.setText(_translate("MainWindow", "Samadhan App"))
        self.Home_button.setText(_translate("MainWindow", "Home"))
        self.Daily_button.setText(_translate("MainWindow", "Daily"))
        self.Weekly_button.setText(_translate("MainWindow", "Weekly"))
        self.Reminder_button.setText(_translate("MainWindow", "Reminder"))
        self.return_button.setText(_translate("MainWindow", "Return"))
        self.addButton.setText(_translate("MainWindow", "Add New"))
        __sortingEnabled = self.tasksListWidget.isSortingEnabled()
        self.tasksListWidget.setSortingEnabled(False)
        item = self.tasksListWidget.item(0)
        item.setText(_translate("MainWindow", "hello"))
        self.tasksListWidget.setSortingEnabled(__sortingEnabled)
        self.saveButton.setText(_translate("MainWindow", "Save Changes"))
<<<<<<< HEAD




import icons_rc




=======
import icons_rc


>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Reminder()
    ui.setupUi(MainWindow)
    MainWindow.show()
<<<<<<< HEAD
    ui.conn = sqlite3.connect('app_screen_time.db')
=======
    ui.conn = sqlite3.connect('data.db')
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
    ui.cursor = ui.conn.cursor()
    ui.sendInitialNotifications()
    timer = QTimer()
    timer.timeout.connect(ui.checkTasksAndSendNotification)
    timer.start(10000)
    sys.exit(app.exec_())
<<<<<<< HEAD


	
=======
>>>>>>> 61c4f9b925991a908c106da378e1746e42f10e93
